routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

Route::resource('event/{events}/form', 'EventFormController', ['except' => 'index', 'show', 'delete']);

Route::middleware(['auth'])->group(function () {
    Route::resource('event', 'EventController');
    Route::resource('participant', 'ParticipantController');
});

app/Events.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Events extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'start_date', 'end_date', 'description','register_start','register_end'
    ];

    public function setEndDateAttribute($value) {
        $this->attributes['end_date'] = \Carbon\Carbon::parse($value)->format('Y-m-d H:i:s');
    }

    public function setStartDateAttribute($value) {
        $this->attributes['start_date'] = \Carbon\Carbon::parse($value)->format('Y-m-d H:i:s');
    }

    public function setRegisterStartAttribute($value) {
        $this->attributes['register_start'] = \Carbon\Carbon::parse($value)->format('Y-m-d H:i:s');
    }

    public function setRegisterEndAttribute($value) {
        $this->attributes['register_end'] = \Carbon\Carbon::parse($value)->format('Y-m-d H:i:s');
    }

    public function getStartDateAttribute($value) {
        return \Carbon\Carbon::parse($value)->format('Y-m-d');
    }

    public function getEndDateAttribute($value) {
        return \Carbon\Carbon::parse($value)->format('Y-m-d');
    }

    public function getRegisterStartAttribute($value) {
        return \Carbon\Carbon::parse($value)->format('Y-m-d');
    }

    public function getRegisterEndAttribute($value) {
        return \Carbon\Carbon::parse($value)->format('Y-m-d');
    }
}

app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;

use App\Participant;
use Illuminate\Http\Request;
use App\Events;

class EventController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $events = Events::all();

        return view('events.index',compact('events'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('events.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $event = new Events;
        $event->fill($request->all());
        $event->save();

        $request->session()->flash('SUCCESS', 'Evenement aangemaakt');
        redirect('event/'.$event->id);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $event = Events::find($id);
        $particiapants = Participant::where('event_id',$id)->get();
        return view('events.show',compact('event','particiapants'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $event = Events::find($id);

        return view('events.edit',['event' => $event]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $event = Events::find($id);
        $event->fill($request->all());
        $event->save();

        $request->session()->flash('SUCCESS', 'Evenement bijgewerkt');
        return redirect('event/'.$event->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id,Request $request)
    {
        $event = Events::find($id);
        $event->delete();

        $request->session()->flash('SUCCESS', 'Evenement verwijderd');
        redirect('event');
    }
}

resources/views/events/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>Evenementen aanmaken</h1>

        <form action="{{route('event.store')}}" method="post">

            @include('events.form',['event' =>  new \App\Events()])

            <button type="submit" class="btn btn-success">Opslaan</button>
        </form>
    </div>
@endsection

resources/views/events/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>Evenementen bewerken</h1>
        <form action="{{route('event.update',$event->id)}}" method="post">
            {!! method_field('patch') !!}
            @include('events.form')

            <button type="submit" class="btn btn-success">Opslaan</button>
        </form>
    </div>
@endsection

resources/views/events/form.blade.php
@include('partials.formError')

{{ csrf_field() }}
<div class="form-group">
    <label>Naam </label>
    <input type="text" class="form-control" name="name" value="{{ old('name',$event->name) }}">
</div>

<div class="form-group">
    <label>Omschrijving</label>
    <input type="text" class="form-control" name="description" value="{{ old('description',$event->description) }}">
</div>

<div class="form-group">
    <label>Evenement start</label>
    <input type="date" class="form-control" name="start_date" value="{{ old('start_date',$event->start_date) }}">
</div>


<div class="form-group">
    <label>Evenement start</label>
    <input type="date" class="form-control" name="end_date" value="{{ old('end_date',$event->end_date) }}">
</div>

<div class="form-group">
    <label>registratie start</label>
    <input type="date" class="form-control" name="register_start" value="{{ old('register_start',$event->register_start) }}">
</div>

<div class="form-group">
    <label>registratie eind</label>
    <input type="date" class="form-control" name="register_end" value="{{ old('register_end',$event->register_end) }}">
</div>

resources/views/events/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
    <h1>Evenementen</h1>

    <p>
        <a href="{{route('event.create')}}" rel="noopener" class="btn btn-success">Maak event aan</a>
    </p>

    <table class="table ">
        <thead>
            <tr>
                <th>#</th>
                <th>naam</th>
                <th>start Datum</th>
                <th>end Datum</th>
                <th></th>
            </tr>
        </thead>

        <tbody>
        @foreach($events as $event)
            <tr>
                <td><a href="{{route('event.show',$event->id)}}">{{$event->id}}</a></td>
                <td>{{$event->name}}</td>
                <td>{{$event->startDate}}</td>
                <td>{{$event->endDate}}</td>
                <td><a href="{{route('event.show',$event->id)}}" class="btn btn-info btn-sm">Detail</a></td>
            </tr>
        @endforeach
        </tbody>
    </table>
    </div>
@endsection

resources/views/events/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <h1>Evenement {{$event->name}}</h1>

        <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
            <div class="btn-group mr-2" role="group" aria-label="First group">
                <a href="{{route('event.edit',$event->id)}}" class="btn btn-info">Bewerken</a>
            </div>
            <div class="btn-group mr-2" role="group" aria-label="Second group">
                <a href="#" class="btn btn-danger">Verwijderen</a>
            </div>
        </div>
        <p>
            Datum:
            <time datetime="{{$event->start_date}}">{{$event->start_date}}</time>
            -
            <time datetime="{{$event->end_date}}">{{$event->end_date}}</time>
        </p>

        <p>
            {{$event->description}}
        </p>

        <strong>Totaal deelnemers: {{$particiapants->count()}}</strong>

        <table class="table table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>Naam</th>
                <th>Geboortedatum</th>
                <th>Mentor</th>
                <th>Betaald</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
                @foreach($particiapants as $participant)
                    <tr>
                        <td>{{$participant->id}}</td>
                        <td>{{$participant->first_name}} {{$participant->last_name}}</td>
                        <td>{{date('d-m-Y', strtotime($participant->birthdate)) }}</td>
                        <td>@if($participant->mentor == 1) <span class="text-success">Ja</span> @else Nee @endif </td>
                        <td>@if($participant->payed == 1) <span class="text-success">Ja</span> @else <span class="text-danger">Nee</span> @endif </td>
                        <td><a href="{{route('participant.show',$participant->id)}}" class="btn btn-sm btn-info">Detail</a> </td>
                    </tr>
                @endforeach
            </tbody>
        </table>

    </div>
@endsection