routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

//Route::get('/home', 'HomeController@index')->name('home');

Route::resource('event/{events}/form', 'EventFormController', ['except' => 'index', 'show', 'delete']);

Route::middleware(['auth'])->group(function () {
    Route::resource('event', 'EventController');
    Route::resource('participant', 'ParticipantController');
});

app/Participant.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Participant extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'event_id', 'first_name', 'last_name', 'sex', 'mentor', 'birthdate', 'email', 'address', 'city', 'phone',
        'phone_emergency', 'department', 'shirt_size', 'allergies', 'diet', 'medical', 'comments', 'document_nr',
        'insurer', 'insurer_number'
    ];

    public function setBirthdateAttribute($value) {
        $this->attributes['birthdate'] = \Carbon\Carbon::parse($value)->format('Y-m-d');
    }
}

app/Http/Controllers/ParticipantController.php
<?php

namespace App\Http\Controllers;

use App\Participant;
use Illuminate\Http\Request;

class ParticipantController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Participant $participant)
    {
        return view('participant.show',['participant' => $participant]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Participant $participant)
    {
        return view('participant.edit',['participant' => $participant]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Participant $participant)
    {
        $participant->fill($request->all());
        $participant->save();

        return redirect('participant/'.$participant->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/participant/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        <form action="{{route('participant.update',[$participant->id])}}" method="post">
            {!! method_field('patch') !!}
            @include('participant.form')

            <button type="submit" class="btn btn-success">Opslaan</button>
        </form>
    </div>
@endsection

resources/views/participant/form.blade.php
@include('partials.formError')

{{ csrf_field() }}
<div class="form-group">
    <label>Voornaam </label>
    <input type="text" class="form-control" name="first_name" value="{{ old('first_name',$participant->first_name) }}" readonly>
</div>

<div class="form-group">
    <label>Voornaam </label>
    <input type="text" class="form-control" name="last_name" value="{{ old('last_name',$participant->last_name) }}" readonly>
</div>

<div class="form-group">
    <label for="payedSelector">Betaald</label>
    <select class="form-control" name="payed" id="payedSelector" required>
        <option value="0" @if(old('payed',$participant->payed) == 0) selected @endif>Nee</option>
        <option value="1" @if(old('payed',$participant->payed) == 1) selected @endif>Ja</option>
    </select>
</div>

<div class="form-group">
    <label for="mentorSelector">Mentor</label>
    <select class="form-control" name="mentor" id="mentorSelector" required>
        <option value="0" @if(old('mentor',$participant->mentor) == 0) selected @endif>Nee</option>
        <option value="1" @if(old('mentor',$participant->mentor) == 1) selected @endif>Ja</option>
    </select>
</div>

resources/views/participant/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <h1>Deelnemer detail</h1>

        <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
            <div class="btn-group mr-2" role="group" aria-label="First group">
                <a href="{{route('participant.edit',$participant->id)}}" class="btn btn-info">Bewerken</a>
            </div>
            <div class="btn-group mr-2" role="group" aria-label="Second group">
                <a href="#" class="btn btn-danger">Verwijderen</a>
            </div>
        </div>

        <table class="table table-bordered">
            <tr>
                <th>Mentor</th>
                <th>Betaald</th>
            </tr>
            <tr>
                <td>@if($participant->mentor == 1) <span class="text-success">Ja</span> @else Nee @endif </td>
                <td>@if($participant->payed == 1) <span class="text-success">Ja</span> @else <span class="text-danger">Nee</span> @endif </td>
            </tr>
        </table>

        <table class="table table-striped table-sm">
            <tbody>

                <tr>
                    <th>ID</th>
                    <td>{{$participant->id}}</td>
                </tr>
                <tr>
                    <th>Geslacht</th>
                    <td>@if($participant->sex == 'M') Man @else Vrouw @endif</td>
                </tr>
                <tr>
                    <th>Voornaam</th>
                    <td>{{$participant->first_name}}</td>
                </tr>
                <tr>
                    <th>Achternaam</th>
                    <td>{{$participant->last_name}}</td>
                </tr>
                <tr>
                    <th>Geboortedatum</th>
                    <td>{{date('d-m-Y',strtotime($participant->birthdate))}}</td>
                </tr>
                <tr>
                    <th>Email</th>
                    <td>{{$participant->email}}</td>
                </tr>
                <tr>
                    <th>Adres</th>
                    <td>{{$participant->address}}</td>
                </tr>
                <tr>
                    <th>Stad</th>
                    <td>{{$participant->city}}</td>
                </tr>
                <tr>
                    <th>Telefoon</th>
                    <td>{{$participant->phone}}</td>
                </tr>
                <tr>
                    <th>Telefoon calamiteiten</th>
                    <td>{{$participant->phone_emergency}}</td>
                </tr>
                <tr>
                    <th>Afdeling</th>
                    <td>{{$participant->department}}</td>
                </tr>
                <tr>
                    <th>Shirt maat</th>
                    <td>{{$participant->shirt_size}}</td>
                </tr>
                <tr>
                    <th>Overig</th>
                    <td>{{$participant->comments}}</td>
                </tr>
            </tbody>
        </table>

    </div>
@endsection